# Generated by Django 3.1 on 2020-09-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_antiga', '0002_registrousuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrousuarios',
            options={'managed': False},
        ),
    ]
